"""Generate Firestore security rules from the permission matrix.

Project IAM cannot express "this identity may write qa_responses but not findings" — the
closest role is a project-wide datastore.user, which is exactly the blanket grant the matrix
exists to avoid. So collection-level access is enforced here, generated from the same file
the README table is generated from. One source of truth, two enforcement points.

Rules are deny-by-default: a collection with no declared reader or writer is readable and
writable by nobody, so adding a collection to the code without adding it to the matrix fails
loudly rather than inheriting someone else's access.

Failure semantics: an identity naming a collection that no other identity declares is
allowed — a collection may legitimately have one writer — but an empty matrix, or one with no
identities, raises rather than emitting a ruleset that would lock the project out.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict

import yaml

HEADER = """\
rules_version = '2';

// Generated by infra/firestore/generate_rules.py from infra/iam/permission-matrix.yaml.
// Do not edit by hand: regenerate instead, or the matrix in the README and the rules applied
// to the project will drift apart.
//
// Deny by default. A collection with no declared reader or writer is reachable by nobody.

service cloud.firestore {
  match /databases/{database}/documents {

    function caller() {
      return request.auth.token.email;
    }
"""

FOOTER = """
    // Anything not named above.
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
"""


class EmptyMatrix(Exception):
    """The matrix declares no identities. Emitting a ruleset from it would lock the project."""


def collect(matrix: dict) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """Return readers and writers per collection, as service account short names."""
    readers: dict[str, list[str]] = defaultdict(list)
    writers: dict[str, list[str]] = defaultdict(list)

    identities = matrix.get("identities") or []
    if not identities:
        raise EmptyMatrix("permission matrix declares no identities")

    for identity in identities:
        fs = identity.get("firestore") or {}
        for collection in fs.get("read") or []:
            readers[collection].append(identity["name"])
        for collection in fs.get("write") or []:
            writers[collection].append(identity["name"])
            # A writer that is not also a declared reader still needs read access to perform a
            # read-modify-write; the matrix states intent, the rules state the mechanics.
            if identity["name"] not in readers[collection]:
                readers[collection].append(identity["name"])

    return readers, writers


def render(readers: dict[str, list[str]], writers: dict[str, list[str]], project: str) -> str:
    out = [HEADER]
    for collection in sorted(set(readers) | set(writers)):
        r = readers.get(collection, [])
        w = writers.get(collection, [])
        out.append(f"\n    match /{collection}/{{doc}} {{")
        out.append(f"      // read:  {', '.join(r) or 'nobody'}")
        out.append(f"      // write: {', '.join(w) or 'nobody'}")
        out.append(f"      allow read: if {_membership(r, project)};")
        out.append(f"      allow write: if {_membership(w, project)};")
        out.append("    }")
    out.append(FOOTER)
    return "\n".join(out)


def _membership(names: list[str], project: str) -> str:
    if not names:
        return "false"
    emails = ", ".join(f"'{n}@{project}.iam.gserviceaccount.com'" for n in sorted(names))
    return f"caller() in [{emails}]"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--matrix", required=True)
    parser.add_argument("--project", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    with open(args.matrix) as fh:
        matrix = yaml.safe_load(fh)

    try:
        readers, writers = collect(matrix)
    except EmptyMatrix as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    with open(args.out, "w") as fh:
        fh.write(render(readers, writers, args.project))

    print(f"wrote {args.out}: {len(set(readers) | set(writers))} collections")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
