"""Generate Firestore security rules from the permission matrix.

Project IAM cannot express "this identity may write qa_responses but not findings" — the
closest role is a project-wide datastore.user, which is exactly the blanket grant the matrix
exists to avoid. So collection-level access is enforced here, generated from the same file
the README table is generated from. One source of truth, two enforcement points.

Rules are deny-by-default: a collection with no declared reader or writer is readable and
writable by nobody, so adding a collection to the code without adding it to the matrix fails
loudly rather than inheriting someone else's access.

**Two shapes, because there are two kinds of collection.** The three platform collections —
``orgs``, ``users``, ``memberships`` — sit at the root. Every other collection lives under
``orgs/{orgId}/``, which is where tenant isolation is enforced: a path is the only way to reach
a customer's data, and the rule for it is scoped to that path. The collection-level matrix is
preserved inside the org block, so both properties hold at once — *which service* may touch a
collection, and *whose copy* of it.

Failure semantics: an identity naming a collection that no other identity declares is
allowed — a collection may legitimately have one writer — but an empty matrix, or one with no
identities, raises rather than emitting a ruleset that would lock the project out.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

HEADER = """\
rules_version = '2';

// Generated by infra/firestore/generate_rules.py from infra/iam/permission-matrix.yaml.
// Do not edit by hand: regenerate instead, or the matrix in the README and the rules applied
// to the project will drift apart.
//
// Deny by default. A collection with no declared reader or writer is reachable by nobody.

service cloud.firestore {
  match /databases/{database}/documents {

    function caller() {
      return request.auth.token.email;
    }

    // A signed-in person, as opposed to one of the fleet's service accounts. Human callers
    // reach their own organisation's data and nothing else; the check is a membership document
    // read, which is why membership ids are `{orgId}:{uid}` rather than a query.
    function isMember(orgId) {
      return request.auth != null
        && request.auth.uid != null
        && exists(/databases/$(database)/documents/memberships/$(orgId + ':' + request.auth.uid))
        && get(/databases/$(database)/documents/memberships/$(orgId + ':' + request.auth.uid))
             .data.status == 'active';
    }

    function memberRole(orgId) {
      return get(/databases/$(database)/documents/memberships/$(orgId + ':' + request.auth.uid))
               .data.role;
    }
"""

FOOTER = """
    // Anything not named above.
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
"""


class EmptyMatrix(Exception):
    """The matrix declares no identities. Emitting a ruleset from it would lock the project."""


def collect(matrix: dict) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    """Return readers and writers per collection, as service account short names."""
    readers: dict[str, list[str]] = defaultdict(list)
    writers: dict[str, list[str]] = defaultdict(list)

    identities = matrix.get("identities") or []
    if not identities:
        raise EmptyMatrix("permission matrix declares no identities")

    for identity in identities:
        fs = identity.get("firestore") or {}
        for collection in fs.get("read") or []:
            readers[collection].append(identity["name"])
        for collection in fs.get("write") or []:
            writers[collection].append(identity["name"])
            # A writer that is not also a declared reader still needs read access to perform a
            # read-modify-write; the matrix states intent, the rules state the mechanics.
            if identity["name"] not in readers[collection]:
                readers[collection].append(identity["name"])

    return readers, writers


GLOBAL_COLLECTIONS = ("orgs", "users", "memberships")
"""The three collections that sit outside any organisation, because they are how organisations
exist. Mirrored from ``shared.tenancy.GLOBAL_COLLECTIONS``; ``tests/test_tenancy.py`` asserts the
two lists agree, because a collection treated as global on one side and tenant-scoped on the
other would be reachable at a path no rule covers."""


def render(readers: dict[str, list[str]], writers: dict[str, list[str]], project: str) -> str:
    out = [HEADER]

    # --- Platform collections, at the root -------------------------------------------------
    out.append(
        "\n    // --- Platform. Outside any organisation, because they are how "
        "organisations exist."
    )
    for collection in GLOBAL_COLLECTIONS:
        r = readers.get(collection, [])
        w = writers.get(collection, [])
        out.append(f"\n    match /{collection}/{{doc}} {{")
        out.append(f"      // read:  {', '.join(r) or 'nobody'}")
        out.append(f"      // write: {', '.join(w) or 'nobody'}")
        if collection == "memberships":
            # A person may read their own membership, and only their own. Without this the
            # isMember() check above could not be evaluated by the caller it is about.
            out.append(
                "      allow read: if "
                + _membership(r, project)
                + " || (request.auth != null && resource.data.uid == request.auth.uid);"
            )
        else:
            out.append(f"      allow read: if {_membership(r, project)};")
        out.append(f"      allow write: if {_membership(w, project)};")
        out.append("    }")

    # --- Tenant collections, under the org that owns them ----------------------------------
    out.append("\n    // --- Tenanted. The path is the isolation: there is no way to name one of")
    out.append("    // these collections without naming the organisation that owns it.")
    out.append("\n    match /orgs/{orgId} {")
    for collection in sorted((set(readers) | set(writers)) - set(GLOBAL_COLLECTIONS)):
        r = readers.get(collection, [])
        w = writers.get(collection, [])
        out.append(f"\n      match /{collection}/{{doc}} {{")
        out.append(f"        // read:  {', '.join(r) or 'nobody'}")
        out.append(f"        // write: {', '.join(w) or 'nobody'}")
        # A service account reaches every tenant, because the fleet works on behalf of all of
        # them; a person reaches only the organisations they belong to. Both conditions are
        # required to read, and only the fleet may write — every human write goes through a
        # service that checks a role first.
        out.append(f"        allow read: if {_membership(r, project)} || isMember(orgId);")
        out.append(f"        allow write: if {_membership(w, project)};")
        out.append("      }")
    out.append("    }")

    out.append(FOOTER)
    return "\n".join(out)


def _membership(names: list[str], project: str) -> str:
    if not names:
        return "false"
    emails = ", ".join(f"'{n}@{project}.iam.gserviceaccount.com'" for n in sorted(names))
    return f"caller() in [{emails}]"


REPO = Path(__file__).resolve().parent.parent.parent
MATRIX_PATH = REPO / "infra" / "iam" / "permission-matrix.yaml"
RULES_PATH = REPO / "infra" / "firestore" / "firestore.rules"


def rules_for(matrix_path: str | Path = MATRIX_PATH, *, project: str) -> str:
    """Return the ruleset the matrix implies, without writing it anywhere.

    The seam the drift test uses: it regenerates from the matrix and compares against the file
    on disk, so a matrix edit that was never regenerated fails in the suite rather than in a
    project six weeks later.
    """
    with open(matrix_path) as fh:
        matrix = yaml.safe_load(fh)
    readers, writers = collect(matrix)
    return render(readers, writers, project)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--matrix", default=str(MATRIX_PATH))
    parser.add_argument("--project", required=True)
    parser.add_argument("--out", default=str(RULES_PATH))
    args = parser.parse_args()

    try:
        body = rules_for(args.matrix, project=args.project)
    except EmptyMatrix as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    with open(args.out, "w") as fh:
        fh.write(body)

    print(f"wrote {args.out}: {body.count('match /') - 2} collections")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
